sudo: required
services:
  - docker

before_install:
  - docker build -t abcosmi/docker-react -f Dockerfile.dev .

script:
  - docker run abcosmi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-675296498696"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
